site_name: Bayesian Change Detection
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_options:
              returns_multiple_items: false
