[project]
name = "bayesian-change-detection"
version = "0.6.1"
description = "Bayesian change detection for input-output sequence data."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.26.4",
    "scipy>=1.15.1",
]
classifiers = ["Private :: Do Not Upload"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "click>=8.1.8",
    "matplotlib>=3.10.0",
    "mypy==1.13.0", # pin due to regression in dmypy 1.14.0
    "pydantic>=2.11.3",
    "pytest>=8.3.5",
    "ruff>=0.9.2",
    "scikit-learn>=1.6.1",
    "tqdm>=4.67.1",
    "types-tqdm>=4.67.0.20241221",
]


[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = [
    "B", # flake8-bugbear
    "E", # pycodestyle errors
    "F", # Pyflakes
    "I", # isort
    "NPY", # NumPy-specific rules
    "RUF", # Ruff-specific rules
    "SLOT", # flake8-slots
    "T10", # flake8-debugger
    "UP", # pyupgrade
    "W", # pycodestyle warnings
]

[tool.mypy]
plugins = ["pydantic.mypy"]

[[tool.mypy.overrides]]
module = "scipy.*,sklearn.*"
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "-Werror"
