name: CI
on:
  push:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1
  test:
    needs: [pre-commit]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.16"
          enable-cache: true
      - name: Install Python dependencies
        run: uv sync --locked
      - name: Python type checking
        run: uv run --frozen mypy .
      - name: Run tests
        run: uv run --frozen pytest -vvv
